<?php

/**
 * PluginGoogleAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfGoogleLoginPlugin
 * @subpackage model
 * @author     Sebastian Herbermann <sebastian.herbermann@googlemail.com>
 */

class PluginGoogleAccount extends BaseGoogleAccount
{
	public function preValidate($event) {
		$object = $event->getInvoker ();
		
		if (! $object->getToken ()) {
			$object->setToken ( sha1 ( $object->getEmail () . rand ( 11111, 99999 ) ) );
		}
	}
}
